function quoteIdentifier(identifier) {
  return `"${String(identifier).replace(/"/g, '""')}"`;
}

async function initializeBusinessSchema(database, schemaName) {
  if (schemaName) {
    await database.query(`CREATE SCHEMA IF NOT EXISTS ${quoteIdentifier(schemaName)} AUTHORIZATION CURRENT_USER;`);
  }

  await database.query(`
    CREATE TABLE IF NOT EXISTS import_batches (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      source_type TEXT NOT NULL,
      import_mode TEXT NOT NULL,
      scope TEXT,
      file_name TEXT,
      status TEXT NOT NULL,
      success_count INTEGER NOT NULL DEFAULT 0,
      failure_count INTEGER NOT NULL DEFAULT 0,
      error_summary TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS employees (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      source_type TEXT NOT NULL,
      employee_no TEXT NOT NULL,
      name TEXT,
      employee_status TEXT,
      base TEXT,
      department TEXT,
      position TEXT,
      channel_type TEXT,
      channel_name TEXT,
      office_location TEXT,
      training_date TEXT,
      entry_date TEXT,
      resigned_date TEXT,
      phone TEXT,
      id_card TEXT,
      handover_date TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(source_type, employee_no)
    );

    CREATE INDEX IF NOT EXISTS idx_employees_role ON employees(position, employee_status);
    CREATE INDEX IF NOT EXISTS idx_employees_base_channel ON employees(base, channel_type);
    CREATE INDEX IF NOT EXISTS idx_employees_training_date ON employees(training_date);

    CREATE TABLE IF NOT EXISTS recruitment_targets (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      year_month TEXT NOT NULL,
      base TEXT NOT NULL,
      channel TEXT NOT NULL,
      order_type TEXT,
      retention_7_rate DOUBLE PRECISION,
      retention_15_rate DOUBLE PRECISION,
      retention_30_rate DOUBLE PRECISION,
      monthly_target INTEGER NOT NULL DEFAULT 0,
      day_targets_json TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX IF NOT EXISTS idx_targets_month_base_channel ON recruitment_targets(year_month, base, channel);

    CREATE TABLE IF NOT EXISTS interview_records (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      base TEXT,
      position_name TEXT,
      candidate_name TEXT,
      gender TEXT,
      phone TEXT,
      feedback_date TEXT,
      feedback_result TEXT,
      interviewer TEXT,
      channel_type TEXT,
      channel_name TEXT,
      channel_tag TEXT,
      contract_name TEXT,
      referrer TEXT,
      evaluation TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX IF NOT EXISTS idx_interviews_feedback_date ON interview_records(feedback_date);
    CREATE INDEX IF NOT EXISTS idx_interviews_result_channel ON interview_records(feedback_result, channel_tag);
    CREATE INDEX IF NOT EXISTS idx_interviews_phone ON interview_records(phone);

    CREATE TABLE IF NOT EXISTS recruiter_monthly_scales (
      year_month TEXT NOT NULL,
      stage TEXT NOT NULL,
      recruiter_count INTEGER NOT NULL DEFAULT 0,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (year_month, stage)
    );

    CREATE TABLE IF NOT EXISTS ai_model_configs (
      provider TEXT PRIMARY KEY,
      base_url TEXT NOT NULL,
      api_key TEXT NOT NULL,
      endpoint TEXT NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
  `);

  await database.query('ALTER TABLE interview_records ADD COLUMN IF NOT EXISTS base TEXT;');
  await database.query('ALTER TABLE interview_records ADD COLUMN IF NOT EXISTS channel_type TEXT;');
  await database.query('ALTER TABLE interview_records ADD COLUMN IF NOT EXISTS channel_name TEXT;');
  await database.query(`
    UPDATE interview_records
    SET channel_type = COALESCE(NULLIF(channel_type, ''), channel_tag),
        channel_name = COALESCE(NULLIF(channel_name, ''), contract_name)
    WHERE channel_type IS NULL
       OR channel_type = ''
       OR channel_name IS NULL
       OR channel_name = '';
  `);
}

module.exports = {
  initializeBusinessSchema
};
